@echo off
REM Ayur-Well Pulse - Quick Start Script for Windows

echo ========================================
echo  Ayur-Well Pulse - Starting Application
echo ========================================
echo.

REM Check if Node.js is installed
where node >nul 2>nul
if %errorlevel% neq 0 (
    echo ERROR: Node.js is not installed!
    echo Please install Node.js from https://nodejs.org/
    pause
    exit /b 1
)

echo [1/4] Checking Node.js version...
node --version
echo.

REM Setup Backend
echo [2/4] Setting up backend server...
cd server

if not exist node_modules (
    echo Installing backend dependencies...
    call npm install
)

if not exist .env (
    echo WARNING: .env file not found!
    echo Please copy .env.example to .env and configure it.
    echo.
    echo Generating secure secrets for you...
    echo.
    
    for /f "tokens=*" %%i in ('node -e "console.log(require('crypto').randomBytes(64).toString('hex'))"') do set JWT_SECRET=%%i
    for /f "tokens=*" %%i in ('node -e "console.log(require('crypto').randomBytes(64).toString('hex'))"') do set JWT_REFRESH_SECRET=%%i
    for /f "tokens=*" %%i in ('node -e "console.log(require('crypto').randomBytes(32).toString('hex').substring(0,32))"') do set ENCRYPTION_KEY=%%i
    for /f "tokens=*" %%i in ('node -e "console.log(require('crypto').randomBytes(16).toString('hex'))"') do set ENCRYPTION_SALT=%%i
    for /f "tokens=*" %%i in ('node -e "console.log(require('crypto').randomBytes(32).toString('hex'))"') do set COOKIE_SECRET=%%i
    
    echo # Auto-generated by start.bat on %date%> .env
    echo # Leave MONGODB_URI blank to run in Mock Mode (no database required)>> .env
    echo MONGODB_URI=>> .env
    echo PORT=5000>> .env
    echo NODE_ENV=development>> .env
    echo JWT_SECRET=%JWT_SECRET%>> .env
    echo JWT_REFRESH_SECRET=%JWT_REFRESH_SECRET%>> .env
    echo JWT_EXPIRATION=15m>> .env
    echo JWT_REFRESH_EXPIRATION=7d>> .env
    echo ALLOWED_ORIGINS=http://localhost:8080,http://localhost:3000>> .env
    echo RATE_LIMIT_WINDOW_MS=900000>> .env
    echo RATE_LIMIT_MAX_REQUESTS=100>> .env
    echo AUTH_RATE_LIMIT_MAX=20>> .env
    echo ENCRYPTION_KEY=%ENCRYPTION_KEY%>> .env
    echo ENCRYPTION_SALT=%ENCRYPTION_SALT%>> .env
    echo COOKIE_SECRET=%COOKIE_SECRET%>> .env
    
    echo .env file created with secure secrets!
    echo.
)

echo Starting backend server on port 5000...
start "AyurWell Backend" cmd /k "npm run dev"
cd ..
echo.

REM Setup Frontend
echo [3/4] Setting up frontend...
if not exist node_modules (
    echo Installing frontend dependencies...
    call npm install
)

echo Starting frontend on port 8080...
start "AyurWell Frontend" cmd /k "npm run dev"
echo.

REM Wait for servers to start
echo [4/4] Waiting for servers to start...
timeout /t 5 /nobreak >nul

echo.
echo ========================================
echo  Application Started Successfully!
echo ========================================
echo.
echo Backend:  http://localhost:5000
echo Frontend: http://localhost:8080
echo Health:   http://localhost:5000/health
echo.
echo Press any key to open the application...
pause >nul

start http://localhost:8080

echo.
echo To stop the application, close the terminal windows.
echo.
pause
